const ACTIONS = {
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',
  ADD_TERCIH: 'ADD_TERCIH',
  DEL_TERCIH: 'DEL_TERCIH',
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  OPEN_MODAL: 'OPEN_MODAL',
};
export default ACTIONS;
