const ACTIONS = {
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',
  ADD_TERCIH: 'ADD_TERCIH',
  DEL_TERCIH: 'DEL_TERCIH',
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  SET_PROVINCE: 'SET_PROVINCE',
  SET_CITY: 'SET_CITY',
  OPEN_MODAL: 'OPEN_MODAL',
  SET_FILTER: 'SET_FILTER',
  SET_CLICKED: 'SET_CLICKED',
  SET_IL: 'SET_IL',
};
export default ACTIONS;
